### ISSUE TITLE
bug - creating design, 

### ISSUE THREAD

**Issue by mariomalnar** [subchannel13/Stareater#97]
selected cruiser, maxed out everything, crashes in end.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Stareater.AppData.Expressions.Variable.Evaluate(IDictionary`2 variables)
   at Stareater.AppData.Expressions.Product.<>c__DisplayClass16.<Evaluate>b__14(Double subProduct, IExpressionNode element)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Stareater.AppData.Expressions.Product.Evaluate(IDictionary`2 variables)
   at Stareater.GameLogic.PlayerProcessor.refitComponentCost[T](Component`1 fromComponent, Component`1 toComponent, Func`2 costFormula, Var extraVars, ShipFormulaSet shipFormulas)
   at Stareater.GameLogic.PlayerProcessor.refitComponentCost[T](List`1 fromComponents, List`1 toComponents, Func`2 costFormula, Var extraVars, ShipFormulaSet shipFormulas)
   at Stareater.GameLogic.PlayerProcessor.refitCost(Design fromDesign, Design toDesign, ShipFormulaSet shipFormulas)
   at Stareater.GameLogic.PlayerProcessor.calcRefitCosts(Design design, ShipFormulaSet shipFormulas)
   at Stareater.GameLogic.PlayerProcessor.Analyze(Design design, StaticsDB statics)
   at Stareater.Controllers.ShipDesignController.Commit()
   at Stareater.GUI.FormShipDesignList.newDesignButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by subchannel13** [comment]
Got it reproduced, extra thrusters cause it.
